### PR TITLE
Feature/get users posts

### LINKED ISSUE #8: Feature: Get user posts
Implement and test out get user posts functionality. Basic use case would be:

1. User sends GET http request to /profile/<:u_id> endpoint
2. Check if user with given id exists in database
3. If user with given id exists in database, do checks:
    - In case the owner profile is public:
        - If there is no jwt token attached, return list of post dtos that have u_id pointing to that user
        - If there is a jwt token attached and owner didn't block the requester, return list of post dtos that have u_id pointing to that user
        - If there is a jwt token attached and there is Block object from owner to requester, return 404
    - In case the owner profile is private:
        - If there is no jwt token attached, return 404
        - If there is a jwt token attached and there is Follow object from requester to owner, return list of post dtos that have u_id pointing to that user
        - Otherwise, return 404
4. If user doesnt exist return 404 response

Get user posts feature should be both unit and integration tested.

### LINKED ISSUE #13: Enhancement: Disable blocked user post viewing
Change getById and getUserPosts methods to check if user that requests posts is blocked by user whose posts are requested.

### PR DESCRIPTION
**Pull request by milosradojcin**

### CODE REVIEW

**Comment by nenad-misic** [comment]
Conflicts appeared. Merge develop to this branch locally and then push.

**Comment by milosradojcin** [comment]
Conflicts resolved.

**Comment by milosradojcin** [comment]
Closing the pull request, the CI didn't do his job.

**Comment by milosradojcin** [comment]
Reopening the pull request, in hope the CI will do its job.

**Review by nenad-misic — APPROVED** [review]

**Pull request merged**
